name: CI Java (Host)

on:
  push:
  workflow_dispatch:

jobs:
    build:
        name: build-sonar-site-upload
        uses: ebpro/gh-actions-shared-java/.github/workflows/ci-shareable-maven.yml@develop
        secrets: inherit
        with:
          maven-args: --errors --batch-mode --show-version --update-snapshots --settings ci-utils-java/ci-settings.xml --color always --no-transfer-progress
          verify-goal: --activate-profiles gpgsigning verify
          run-on: arc-runner-set
