name: Delete Old Snpashot Package  # on every push
on: [push]
jobs:
  cleanup:
    # The tags on the runner
    runs-on: [self-hosted, Linux]
    steps:
        - uses: smartsquaregmbh/delete-old-packages@v0.3.2
          with:
            keep: 1
            names: |
              fr.univtln.bruno.demos.poms.demoparentpom
